docs:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']
tests:
  - changed-files:
      - any-glob-to-any-file: ['tests/**']
ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']
ports:
  - changed-files:
      - any-glob-to-any-file: ['ports/**']
